#cloud-config
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - curl
  - git
  - jq
  - docker.io
  - docker-compose-v2
runcmd:
  - [bash, -lc, "systemctl enable --now docker"]
  - [bash, -lc, "usermod -aG docker ubuntu"]
